# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Continous Delivery

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

permissions:
  id-token: write
  contents: read
  actions: read
  issues: write

env:
  ARTIFACT_DIR: publish
  ARTIFACT_NAME: build_artifact
  RESOURCE_GROUP: dagger-test
  WEB_APP: dagger-webapp
  LOCATION: west europe

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"

      - name: Download CI workflow artifact
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          workflow: ci.yml
          name: build_artifact
          path: ${{ env.ARTIFACT_DIR }}
          skip_unpack: true

      - name: Deploy to staging slot
        run: |
          go run main.go -m cd \
                         -s tenantId=${{ secrets.AZURE_TENANT_ID }} \
                         -s appId=${{ secrets.AZURE_APP_ID }} \
                         -s password=${{ secrets.AZURE_PASSWORD }} \
                         -v ResourceGroupName=${{ env.RESOURCE_GROUP }} \
                         -v WebAppName=${{ env.WEB_APP }} \
                         -v Location=${{ env.LOCATION }} \
                         -v ArtifactName=${{ env.ARTIFACT_NAME }} \
                         -a ${{ env.ARTIFACT_DIR }} \
                         -f deployToStaging
  swap:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: pbakun
          issue-title: "Deploying application to prod from staging"
          issue-body: "Please approve or deny the deployment for application."

      - name: Swap staging and production slot
        run: |
          go run main.go -m cd \
                          -s tenantId=${{ secrets.AZURE_TENANT_ID }} \
                          -s appId=${{ secrets.AZURE_APP_ID }} \
                          -s password=${{ secrets.AZURE_PASSWORD }} \
                          -v ResourceGroupName=${{ env.RESOURCE_GROUP }} \
                          -v WebAppName=${{ env.WEB_APP }} \
                          -v Location=${{ env.LOCATION }} \
                          -v ArtifactName=${{ env.ARTIFACT_NAME }} \
                          -a ${{ env.ARTIFACT_DIR }} \
                          -f deployToStaging