# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Continous Integration

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ ".github/workflows/cd.yml" ]
  pull_request:
    branches: [ "master" ]

env:
  OUTPUT_DIR: ./build

permissions:
  actions: read
  contents: read
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ">=1.20"

    - name: Build Application
      run: go run main.go -m ci -o ${{ env.OUTPUT_DIR }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build_artifact
        path: ${{ env.OUTPUT_DIR }}
