# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ">=1.20"

    - name: Build Application
      run: go run main.go
    - name: Bash Action
      uses: rethab/bash-action@v1
      with:
        command: "echo ls"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build_Artifact
        path: ${GITHUB_ACTION_PATH}/build
